### ISSUE TITLE
cannot import name 'ROCKROBO_S7_MAXV' after update to HomeAssistant 2022.11.2

### ISSUE THREAD

**Issue by zelial** [rytilahti/python-miio#1584]
**Describe the bug**
After an update from HA 2022-10.5 to HA 2022-11.2 I'm getting this error in the logs:

2022-11-09 10:41:06.272 ERROR (MainThread) [homeassistant.setup] Setup failed for xiaomi_miio: Unable to import component: cannot import name 'ROCKROBO_S7_MAXV' from 'miio.vacuum' (/config/deps/lib/python3.10/site-packages/miio/vacuum.py)

**Version information (please complete the following information):**
 - OS: HomeAssistant 2022-11.2 container  (Alpine 3.16.2)
 - python-miio: 0.5.12

It works on HA 2022-10.5 container (Alpine 3.16.0) with python-miio also at 0.5.12

**Device information:**
I'm using it to enable support for viomi.vacuum.v8 via https://github.com/nergal/homeassistant-vacuum-viomi

**To Reproduce**
Update to HA 2022-11.2

**Expected behavior**
No import error, 

**Console output**

**Comment by rytilahti** [comment]
That custom component needs to update the pinning, otherwise it forces installation of an old version that does not have the `ROCKROBO_S7_MAXV` constant. This is not a problem in this library, so I'm closing this: https://github.com/nergal/homeassistant-vacuum-viomi/blob/master/custom_components/xiaomi_viomi/manifest.json#L12
